"""
BITWISE OPERATORS (BASED ON BINARY, It converts the given two value to binary number)
&   AND (CONVERTS BINARY TO DECIMAL USING AND GATE)
|   OR  (CONVERTS BINARY TO DECIMAL USING OR GATE)
^   XOR (CONVERTS BINARY TO DECIMAL USING XOR GATE)
IF(and)  0 1 0 1
         0 0 1 1
OUTPUT   0 0 0 1
IF(or)   0 1 0 1
         0 0 1 1
OUTPUT   0 1 1 1
IF(XOR)  0 1 0 1
         0 0 1 1
OUTPUT   0 1 1 0
20(DECIMAL) 010100(BINARY)
40(DECIMAL) 101000(BINARY)
~   NOT (ADD ONE TO GIVEN VALUE AND SEND OUTPUT WITH -SIGN)
<<  ZERO FILL LEFT SHIFT  (CONVERTS THE GIVEN TO HEXADECIMAL AND SHIFTS THE LEFT BIN TO RIGHT SIDE AND SENDS OUTPUT IN DECIMAL VALUE)
20 010100
STEP 1 : CONVERT TO HEXADECIMAL 00010100
STEP 2 : IF <<2 SHIFT LEFT SIDE VALUE TO RIGHT SIDE 01010000
STEP 3 : COVERT IT TO DECIMAL AND SENDS OUTPUT
>>  SIGNED RIGHT SHIFT  (SAME AS ZERO FILL LEFT SHIFT BUT SHIFT FROM RIGHT SIDE TO LEFT SIDE)
"""
a=20
b=40
print(a&b)
print(a|b)
print(a^b)
print(~a)
print(a<<2)
print(a>>2)

